#chapet6
a<-c("y","y","n","n","n","y","y","n")
f1<-factor(a)
b<-c("y","y","n","n","n","y","y","n","m","m")
f2<-factor(b)
c<-c("y","y","n","n","n","y","y","n","m","m")
f3<-factor(c, levels=c("y","n","m","p"))
str(f3)
c<-c("y","y","n","n","n","y","y","n","m","m","p","p")
f3<-factor(c, levels=c("y","n","m","p"))
str(f3)
f3_num<-as.numeric(f3)
temp<-c(26, 27,28, 34,32, 27,28,32,25)
ftemp<-factor(temp)
as.numeric(ftemp)
temp2<-as.numeric(as.character(ftemp))
c<-c("y","y","n","n","n","y","y","n","m","m","p","p")
f4<-ordered(c)
str(f4)
table(state.region)

st1<-c("A","B","C","D","F","C","A","B","C","F","D","A","B","C","A","D","F","A","B","C")
st_level<-factor(st1, levels=c("F","D","C","B","A"), order=TRUE)
st_level
which(st_level>"B")
which(st_level<="F")
tail(st_level)
#chapter7
m.name<-c("kevin", "peter", "frank", "maggie")
m.gender <- c("M","M","M","F")
m.height <- c(170, 175, 165, 168)
m.info <- data.frame(m.name, m.gender, m.height, stringsAsFactors = FALSE)
names(m.info) <- c("name","gender","height")
m.info<-rbind(m.info, c("amy","F",161))
m.newinfo<-data.frame(name=c("tony","julis"), gender=c("M","F"), height=c(171,163))
m.newinfo2<-rbind(m.info, m.newinfo)
weight <- c(77,65,67,57, 58)
m.info$weight <- weight

head(iris)
